# -*- coding: utf-8 -*-
"""chuyendoippt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZddcCnSvkimLOTGjtjMQydba7fvQfve
"""

!pip install python-pptx

!pip install python-docx

from google.colab import files
from pptx import Presentation
from pptx.util import Inches, Pt
import docx
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import ipywidgets as widgets
from IPython.display import display

def read_docx(file_path):
    doc = docx.Document(file_path)
    paragraphs = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
    return paragraphs

def read_txt(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        lines = [line.strip() for line in file.readlines() if line.strip()]
    return lines

def create_ppt_from_file(file_name):
    if file_name.endswith(".docx"):
        content = read_docx(file_name)
    elif file_name.endswith(".txt"):
        content = read_txt(file_name)
    else:
        print("Định dạng file không được hỗ trợ!")
        return

    # Tạo một file trình bày mới
    prs = Presentation()

    for i, para in enumerate(content):
        if i == 0:  # Slide tiêu đề
            slide = prs.slides.add_slide(prs.slide_layouts[0])  # Layout tiêu đề
            title = slide.shapes.title
            title.text = para
            title.text_frame.paragraphs[0].font.size = Pt(44)  # Cỡ chữ lớn
            title.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER  # Căn giữa
        else:  # Các slide nội dung
            slide = prs.slides.add_slide(prs.slide_layouts[1])  # Layout tiêu đề + nội dung
            title = slide.shapes.title
            content_box = slide.shapes.placeholders[1]
            title.text = f"{i}. {para[:50]}..." if len(para) > 50 else para  # Tiêu đề ngắn gọn
            text_frame = content_box.text_frame
            text_frame.text = para

            # Định dạng văn bản
            text_frame.paragraphs[0].font.size = Pt(28)  # Cỡ chữ
            text_frame.paragraphs[0].alignment = PP_ALIGN.LEFT  # Căn trái

    output_pptx = "output_presentation.pptx"
    prs.save(output_pptx)
    print(f"Đã tạo file: {output_pptx}")
    files.download(output_pptx)

# Giao diện tải file đẹp
upload_button = widgets.FileUpload(accept='.docx,.txt', multiple=False)
display(upload_button)

def on_upload_change(change):
    if upload_button.value:
        file_name = list(upload_button.value.keys())[0]
        with open(file_name, "wb") as f:
            f.write(upload_button.value[file_name]["content"])
        create_ppt_from_file(file_name)

upload_button.observe(on_upload_change, names='value')